language: node_js
dist: jammy
node_js:
  - '22'
addons:
  chrome: stable
env:
  global:
    - NODE_ENV="test"
    - 'TEST_SERVER="https://hallebot.operationspark.org"'
    - OWNER=`echo $TRAVIS_REPO_SLUG | cut -d '/' -f 1`
    - REPO=`echo $TRAVIS_REPO_SLUG | cut -d '/' -f 2`
    - GIT_BRANCH=`echo $TRAVIS_PULL_REQUEST_BRANCH`
    - 'CODE_DIR=`if [[ $REPO == "course."* ]]; then echo "code"; else echo "."; fi`'
before_install:
  - echo $OWNER
  - echo $REPO
  - echo $CODE_DIR
  - echo $GIT_BRANCH
install:
  - yarn --cwd $CODE_DIR/
  - yarn --cwd $CODE_DIR/.ci/
  - 'PATH=$PATH:./node_modules/.bin'
  - 'PATH=$PATH:../node_modules/.bin'
script:
  - '[[ "$OWNER" == "OperationSpark" ]]'
  - curl --silent --output $CODE_DIR/_test.js $TEST_SERVER/scripts/test.js
  - node $CODE_DIR/_test.js $REPO $TEST_SERVER $CODE_DIR $GIT_BRANCH
notifications:
  webhooks: 'https://greenlight.operationspark.org/api/v2/webhooks/travisci'
